### ISSUE TITLE
clickable icons

### ISSUE THREAD

**Issue by unpickme** [4Ax-Technologies/capture_device1#1]
![4Ax sphere_icon](https://github.com/4Ax-Technologies/capture_device1/assets/90104815/917ff0be-b126-47b4-bf80-e8c2a6a2acfa)
![LinkedIn_icon](https://github.com/4Ax-Technologies/capture_device1/assets/90104815/ff94652e-75f2-4f6d-8351-f1ecd4d756cb)

**Comment by greatwhite9** [comment]
Can you please elaborate what action you want on clicking the icon

**Comment by unpickme** [comment]
Hi great white

I am setting up these clickable icons to link to my site and my LinkedIn site. Could you please explain how I get back to the code for the second icon (to copy/paste it into my README.md file) I think I have the rest of it set up.

Many thanks

**Comment by unpickme** [comment]
Hi again great white

I worked around the issue above by re-uploading the second icon. However when I click on either of the icons a copy of the icon downloads to a new tab in my browser (linking to the Github location of the icon), rather than opening the appropriate site in a new tab.

I am using the instructions described at:
https://github.com/nomi811/clickable-icons-to-readme#:~:text=On%20your%20repo%20that%20you,want%20the%20icon%20to%20appear.

e.g
[![github](https://cloud.githubusercontent.com/assets/17016297/18839843/0e06a67a-83d2-11e6-993a-b35a182500e0.png)][1]

where the content in the first set of square brackets is the link created by dragging and dropping your image file into the repo issue window and the [1] at the end corresponds to the numbered link you will create in the next step.

At the bottom of the file, create a numbered list for all your various account links. The code will be in this format:

[1]: http://www./your_contact_info

**Comment by unpickme** [comment]
Hi again

I fixed it. I dropped the first square bracket when copy/pasting the link code

Embarrassed face emoji

Cheers
